export const MY_TEAM = {
  name: "Sales",
  id: "auzgeiugaze",
  members: [
    {
      firstName: "Noé",
      lastName: "C",
      profilePic: "",
      email: "noe.c@acme.co",
      role: "Senior lead Manager",
      id: "mate-1",
      lastUpdate: "2022-06-18",
      createdDate: "2022-06-15",
      lastActivity: "2022-06-30",
      userPerm: "editor",
    },
    {
      firstName: "Clément",
      lastName: "P",
      profilePic: "",
      email: "clement.p@acme.co",
      role: "Senior Sales Manager",
      id: "mate-2",
      lastUpdate: "2022-06-18",
      createdDate: "2022-06-15",
      lastActivity: "2022-06-25",
      userPerm: "editor",
    },
    {
      firstName: "Némo",
      lastName: "F",
      profilePic: "",
      email: "nem.f@acme.co",
      role: "Senior Sales",
      id: "mate-3",
      lastUpdate: "2022-06-18",
      createdDate: "2022-06-15",
      lastActivity: "2022-06-25",
      userPerm: "onboardee",
    },
    {
      firstName: "Constance",
      lastName: "D",
      profilePic: "",
      email: "constance.d@acme.co",
      role: "Senior Sales",
      id: "mate-4",
      lastUpdate: "2022-06-18",
      createdDate: "2022-06-15",
      lastActivity: "2022-06-25",
      userPerm: "onboardee",
    },
    {
      firstName: "Théa",
      lastName: "D",
      profilePic: "",
      email: "theadosto@acme.co",
      role: "Sales apprentice",
      id: "mate-5",
      lastUpdate: "2022-07-01",
      createdDate: "2022-06-15",
      lastActivity: "2022-06-25",
      userPerm: "onboardee",
    },
  ],
};
