const doc = {
    templates: [
        {
            id: "template-1",
            name: "Bienvenue chez nous !",
            status: "toAssign",
            lastUpdate: "2022-06-01",
            tags: ["Tout", "Junior"],
            users: ["a", "b", "c"],
            teamName: 'Sales',
            progress: 45,
            docs: ['doc id'],
        },
        {
            id: "template-2",
            name: "Découvrir l'équipe",
            status: "toAssign",
            lastUpdate: "2022-06-01",
            tags: ["Tout", "Junior"],
            users: ["a", "b", "c"],
            teamName: 'Sales',
            progress: 20,
            docs: ['doc id'],
        },
        {
            id: "template-3",
            name: "La vie chez Acme.co ",
            status: "toAssign",
            lastUpdate: "2022-06-01",
            tags: ["Tout", "Junior"],
            users: ["a", "b", "c"],
            teamName: 'Sales',
            progress: 100,
            docs: ['doc id'],
        },
        {
            id: "template-4",
            name: "La vente chez Acme.co",
            status: "toAssign",
            lastUpdate: "2022-06-01",
            tags: ["Tout", "Junior"],
            users: ["a", "b", "c"],
            teamName: 'Sales',
            progress: 0,
            docs: ['doc id'],
        },
        {
            id: "template-5",
            name: "Les missions de l'account Executive",
            status: "toAssign",
            lastUpdate: "2022-06-01",
            tags: ["Tout", "Junior"],
            users: ["a", "b", "c"],
            teamName: 'Sales',
            progress: 30,
            docs: ['doc id'],
        },
        {
            id: "template-6",
            name: "Les comptes et outils à configurer",
            status: "toAssign",
            lastUpdate: "2022-06-01",
            tags: ["Tout", "Junior"],
            users: ["a", "b", "c"],
            teamName: 'Sales',
            progress: 90,
            docs: ['doc id'],
        },
        {
            id: "template-7",
            name: "Les outils pour les sales",
            status: "toAssign",
            lastUpdate: "2022-06-01",
            tags: ["Tout", "Junior"],
            users: ["a", "b", "c"],
            teamName: 'Sales',
            progress: 40,
            docs: ['doc id'],
        },
],
    documents: [
        {
            name: 'Contrat-de-travail.pdf',
            uploadName: 'contrat de travail',
            uploadDate: '2022-06-22',
            teamName: 'Resource Humaine',
            templateName: 'Arriver',
            date: '2022-04-22',
            status: 'toLate',
            id: 'azeaze',
        },
        {
            name: 'charte-informatique.pdf',
            uploadName: 'Charte informatique',
            uploadDate: '2022-06-22',
            teamName: 'Resource Humaine',
            templateName: 'Arriver',
            date: '2022-04-22',
            status: 'good',
            id: 'azeaze',
        },
    ],
}

export const MY_TEAM = {
  name: "Sales",
  id: "auzgeiugaze",
  members: [
    {
      firstName: "Noé",
      lastName: "C",
      profilePic: "",
      email: "noe.c@acme.co",
      role: "Senior lead Manager",
      id: "mate-1",
      lastUpdate: "2022-06-18",
      createdDate: "2022-06-15",
      lastActivity: "2022-06-30",
      userPerm: "editor",
      ...doc
      
    },
    {
      firstName: "Clément",
      lastName: "P",
      profilePic: "",
      email: "clement.p@acme.co",
      role: "Senior Sales Manager",
      id: "mate-2",
      lastUpdate: "2022-06-18",
      createdDate: "2022-06-15",
      lastActivity: "2022-06-25",
      userPerm: "editor",
      ...doc
    },
    {
      firstName: "Némo",
      lastName: "F",
      profilePic: "",
      email: "nem.f@acme.co",
      role: "Senior Sales",
      id: "mate-3",
      lastUpdate: "2022-06-18",
      createdDate: "2022-06-15",
      lastActivity: "2022-06-25",
      userPerm: "onboardee",
      ...doc
    },
    {
      firstName: "Constance",
      lastName: "D",
      profilePic: "",
      email: "constance.d@acme.co",
      role: "Senior Sales",
      id: "mate-4",
      lastUpdate: "2022-06-18",
      createdDate: "2022-06-15",
      lastActivity: "2022-06-25",
      userPerm: "onboardee",
      ...doc
    },
    {
      firstName: "Théa",
      lastName: "D",
      profilePic: "",
      email: "theadosto@acme.co",
      role: "Sales apprentice",
      id: "mate-5",
      lastUpdate: "2022-07-01",
      createdDate: "2022-06-15",
      lastActivity: "2022-06-25",
      userPerm: "onboardee",
      ...doc
    },
  ],
};

